language: android

jdk:
  - oraclejdk8

env:
  global:
   - ANDROID_API_LEVEL=25
   - EMULATOR_API_LEVEL=24
   - ANDROID_BUILD_TOOLS_VERSION=24.0.0

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL

# if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

# Support library
    - extra-android-support
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck


licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


